// utils.js
// Shared utility functions for the ESBD project.

import { render as katexRender } from 'katex';
import renderMathInElement from 'katex/contrib/auto-render';

/**
 * Creates the base HTML content for a popup based on diagram info object.
 * Generic version that does not depend on external config.
 * @param {object} info - The info object from the ESBD callback.
 * Expected fields: labelString, speciesId, traceId, curveType,
 * xValue, yValueDisplayed, currentMode, regionInfo.
 * @returns {string} - Basic HTML string for the popup, using KaTeX delimiters.
 */
export function formatPopupBaseContent(info) {
    let label = info.label; // The KaTeX string generated by the module (no delimiters)
    if (label) {
        label = `$${label}$`; // Add delimiters for KaTeX auto-render
    } else {
        // Fallback using speciesId or traceId if label is null/undefined
        label = info.speciesId || info.traceId || 'Trace';
    }

    const description = info.curveDescription;
    // --- Format Title Line ---
    // REFACTOR: Assemble title line separately
    const titleLine = `<b>${label}</b>: ${description}`;

    // Format position
    let positionStr = `x = ${info.xValue?.toFixed(3)}`; // Add optional chaining

    // Format value
    let valueStr = `y = ${info.yValue.toFixed(3)}&nbsp;V`;

    // Format region
    let regionStr = '';
    if (info.regionInfo) {
        regionStr = `Region: ${info.regionInfo.name} (#${info.regionIndex})`;
    }

    // Assemble Final Content
    let content = titleLine;
    content += `<br>${positionStr}`;
    content += `<br>${valueStr}`;
    if (regionStr) content += `<br>${regionStr}`;

    return content;
}

// ========================================================================
// Debounce and Throttle Utilities
// Based on common patterns (similar to Lodash implementations)
// ========================================================================

/**
 * Creates a debounced function that delays invoking func until after wait milliseconds
 * have elapsed since the last time the debounced function was invoked.
 * Includes a .cancel() method to cancel delayed func invocations.
 * @param {Function} func The function to debounce.
 * @param {number} wait The number of milliseconds to delay.
 * @returns {Function & { cancel: () => void }} Returns the new debounced function with a cancel method.
 */
export function debounce(func, wait) {
    let timeoutId = null; // Store timeout ID accessible by returned function and cancel method

    const debounced = function executedFunction(...args) {
        const context = this;
        const later = () => {
            timeoutId = null;
            func.apply(context, args);
        };
        clearTimeout(timeoutId);
        timeoutId = setTimeout(later, wait);
    };

    debounced.cancel = function () {
        clearTimeout(timeoutId);
        timeoutId = null;
    };

    return debounced;
}

/**
 * Creates a throttled function that only invokes func at most once per every wait milliseconds.
 * Includes options for leading and trailing calls and a .cancel() method.
 * @param {Function} func The function to throttle.
 * @param {number} wait The number of milliseconds to throttle invocations to.
 * @param {object} [options={}] Optional configuration.
 * @param {boolean} [options.leading=true] Specify invoking on the leading edge of the timeout.
 * @param {boolean} [options.trailing=true] Specify invoking on the trailing edge of the timeout.
 * @returns {Function & { cancel: () => void }} Returns the new throttled function with a cancel method.
 */
export function throttle(func, wait, options = {}) {
    let context, args, result;
    let timeoutId = null;
    let previous = 0; // Timestamp of the last execution
    if (!options) options = {};
    const leading = options.leading !== false; // Default true
    const trailing = options.trailing !== false; // Default true

    const later = function () {
        previous = leading === false ? 0 : Date.now(); // Reset previous if leading is false
        timeoutId = null;
        result = func.apply(context, args); // Execute the function
        if (!timeoutId) context = args = null; // Clear references if no pending timeout
    };

    const throttled = function () {
        const now = Date.now();
        // If leading is false and this is the first call, set previous to now
        if (!previous && leading === false) previous = now;

        const remaining = wait - (now - previous);
        context = this;
        args = arguments;

        if (remaining <= 0 || remaining > wait) {
            // If time expired or system clock changed drastically
            if (timeoutId) {
                clearTimeout(timeoutId);
                timeoutId = null;
            }
            previous = now;
            result = func.apply(context, args); // Execute immediately
            if (!timeoutId) context = args = null;
        } else if (trailing && !timeoutId) {
            // Schedule trailing call if option enabled and no timer currently pending
            timeoutId = setTimeout(later, remaining);
        }
        return result;
    };

    throttled.cancel = function () {
        clearTimeout(timeoutId);
        previous = 0;
        timeoutId = context = args = null;
    };

    return throttled;
}

/**
 * Renders LaTeX mathmode inside a given span element, but only if the new label
 * text is different from the previously rendered text (stored in dataset).
 * Handles clearing old content and potential KaTeX errors.
 * @param {HTMLSpanElement} spanElement - The target span element.
 * @param {string | null | undefined} newLabelText - The raw LaTeX string (no delimiters) or null/empty to clear.
 * @param {boolean} textMode - Start in text mode or in math mode (default).
 * @param {boolean} forceRender - Render anyway even if label was unchanged.
 */
export function renderSpanMath(
    spanElement,
    newLabelText,
    textMode = false,
    forceRender = false
) {
    if (!spanElement) return; // Safety check

    const currentLabel = newLabelText ?? '';

    if (typeof katexRender === 'undefined') {
        // Caller forgot to load katex
        spanElement.textContent = currentLabel;
        return;
    }

    // For text mode, we also need the auto-render extension.
    if (textMode && typeof renderMathInElement === 'undefined') {
        console.warn(
            'KaTeX auto-render extension not loaded for text mode rendering.'
        );
        spanElement.innerHTML = currentLabel;
        return;
    }

    const previousLabel = spanElement.dataset.renderedLabel || '';
    const currentMode = textMode ? 'text' : 'math';
    const previousMode = spanElement.dataset.renderedMode || currentMode;

    // Avoid re-rendering if no change in content or mode
    if (
        currentLabel === previousLabel &&
        currentMode === previousMode &&
        !forceRender
    )
        return;

    // Update stored label and mode first
    spanElement.dataset.renderedLabel = currentLabel;
    spanElement.dataset.renderedMode = currentMode;

    // Clear existing content
    spanElement.innerHTML = '';
    if (!currentLabel) return;

    try {
        if (textMode) {
            spanElement.innerHTML = currentLabel;
            renderMathInElement(spanElement, {
                delimiters: [{ left: '$', right: '$', display: false }],
                throwOnError: false,
            });
        } else {
            katexRender(currentLabel, spanElement, {
                throwOnError: false,
                displayMode: false,
            });
        }
    } catch (e) {
        console.error('KaTeX render error:', e, '| Input:', currentLabel);
        spanElement.textContent = currentLabel; // Fallback on error
    }
}

// ========================================================================
// Numerics
// ========================================================================

export function linspace(start, end, numPoints) {
    if (numPoints < 2) {
        return numPoints === 1 ? [start] : [];
    }
    const arr = [];
    const step = (end - start) / (numPoints - 1);
    for (let i = 0; i < numPoints; i++) {
        arr.push(start + step * i);
    }
    return arr;
}

// ========================================================================
// Controls
// ========================================================================

/**
 * Wires an already-present (static-HTML) <input type="range"> to a throttled
 * callback. The markup must exist in the page at load time — we never inject it
 * from JS, to avoid layout shift. Pair with the `slider` njk macro in
 * `_includes/macros/controls.njk`.
 *
 * @param {string} id - id of the range input element.
 * @param {(value:number, event:Event|null)=>void} onInput - called with the parsed numeric value.
 * @param {object} [opts]
 * @param {number} [opts.throttleMs=100] - throttle interval in ms; 0 disables throttling.
 * @param {boolean} [opts.fire=true] - also invoke onInput once immediately with the initial value.
 * @returns {HTMLInputElement} the slider element.
 */
export function makeSlider(id, onInput, { throttleMs = 100, fire = true } = {}) {
    const el = document.getElementById(id);
    if (!el) throw new Error(`makeSlider: no element #${id}`);
    const call = (event) => onInput(parseFloat(el.value), event);
    el.addEventListener('input', throttleMs ? throttle(call, throttleMs) : call);
    if (fire) onInput(parseFloat(el.value), null);
    return el;
}

// ========================================================================
// bandScale — a band scale with sane padding semantics
// ========================================================================

/**
 * Replacement for d3.scaleBand with predictable semantics (d3's version
 * clamps its step formula with max(1, n - paddingInner + 2*paddingOuter),
 * so with a single band paddingOuter is silently ignored and the band can
 * never fill the range — see d3-scale/src/band.js).
 *
 * Here paddings are fractions of the BANDWIDTH and everything tiles the
 * range exactly:  range = [pOut*bw][bw][pIn*bw][bw]...[bw][pOut*bw]
 * so paddingInner only matters for n >= 2, paddingOuter works for ALL n,
 * and with paddingOuter=0 the outer band edges sit exactly on the range
 * ends (no hidden leftover, hence no align knob at all).
 *
 * Duck-type compatible with d3-axis (callable + domain/range/bandwidth/copy).
 */
export function bandScale() {
    let domainVals = [];
    let r0 = 0,
        r1 = 1;
    let pIn = 0,
        pOut = 0;
    let index = new Map();
    let bw = 0,
        stepv = 0;

    function rescale() {
        const n = domainVals.length;
        if (n === 0) {
            index = new Map();
            bw = stepv = 0;
            return scale;
        }
        bw = (r1 - r0) / (n + (n - 1) * pIn + 2 * pOut);
        stepv = bw * (1 + pIn);
        index = new Map(
            domainVals.map((d, i) => [d, r0 + pOut * bw + i * stepv])
        );
        return scale;
    }

    function scale(d) {
        return index.get(d);
    }

    scale.domain = function (_) {
        return arguments.length
            ? ((domainVals = Array.from(_)), rescale())
            : domainVals.slice();
    };
    scale.range = function (_) {
        return arguments.length
            ? (([r0, r1] = _), (r0 = +r0), (r1 = +r1), rescale())
            : [r0, r1];
    };
    scale.paddingInner = function (_) {
        return arguments.length ? ((pIn = +_), rescale()) : pIn;
    };
    scale.paddingOuter = function (_) {
        return arguments.length ? ((pOut = +_), rescale()) : pOut;
    };
    scale.bandwidth = () => bw;
    scale.step = () => stepv;
    // d3-axis's band-centering helper calls scale.round(); we don't round.
    scale.round = () => false;
    scale.copy = () =>
        bandScale()
            .paddingInner(pIn)
            .paddingOuter(pOut)
            .domain(domainVals)
            .range([r0, r1]);

    return scale;
}
