// utils.js
// Shared utility functions for the ESBD project.

import { render as katexRender } from 'katex';
import renderMathInElement from 'katex/contrib/auto-render';

/**
 * Creates the base HTML content for a popup based on diagram info object.
 * Generic version that does not depend on external config.
 * @param {object} info - The info object from the ESBD callback.
 * Expected fields: labelString, speciesId, traceId, curveType,
 * xValue, yValueDisplayed, currentMode, regionInfo.
 * @returns {string} - Basic HTML string for the popup, using KaTeX delimiters.
 */
export function formatPopupBaseContent(info) {
    let label = info.label; // The KaTeX string generated by the module (no delimiters)
    if (label) {
        label = `$${label}$`; // Add delimiters for KaTeX auto-render
    } else {
        // Fallback using speciesId or traceId if label is null/undefined
        label = info.speciesId || info.traceId || 'Trace';
    }

    const description = info.curveDescription;
    // --- Format Title Line ---
    // REFACTOR: Assemble title line separately
    const titleLine = `<b>${label}</b>: ${description}`;

    // Format position
    let positionStr = `x = ${info.xValue?.toFixed(3)}`; // Add optional chaining

    // Format value
    let valueStr = `y = ${info.yValue.toFixed(3)}&nbsp;V`;

    // Format region
    let regionStr = '';
    if (info.regionInfo) {
        regionStr = `Region: ${info.regionInfo.name} (#${info.regionIndex})`;
    }

    // Assemble Final Content
    let content = titleLine;
    content += `<br>${positionStr}`;
    content += `<br>${valueStr}`;
    if (regionStr) content += `<br>${regionStr}`;

    return content;
}

// ========================================================================
// Debounce and Throttle Utilities
// Based on common patterns (similar to Lodash implementations)
// ========================================================================

/**
 * Creates a debounced function that delays invoking func until after wait milliseconds
 * have elapsed since the last time the debounced function was invoked.
 * Includes a .cancel() method to cancel delayed func invocations.
 * @param {Function} func The function to debounce.
 * @param {number} wait The number of milliseconds to delay.
 * @returns {Function & { cancel: () => void }} Returns the new debounced function with a cancel method.
 */
export function debounce(func, wait) {
    let timeoutId = null; // Store timeout ID accessible by returned function and cancel method

    const debounced = function executedFunction(...args) {
        const context = this;
        const later = () => {
            timeoutId = null;
            func.apply(context, args);
        };
        clearTimeout(timeoutId);
        timeoutId = setTimeout(later, wait);
    };

    debounced.cancel = function () {
        clearTimeout(timeoutId);
        timeoutId = null;
    };

    return debounced;
}

/**
 * Creates a throttled function that only invokes func at most once per every wait milliseconds.
 * Includes options for leading and trailing calls and a .cancel() method.
 * @param {Function} func The function to throttle.
 * @param {number} wait The number of milliseconds to throttle invocations to.
 * @param {object} [options={}] Optional configuration.
 * @param {boolean} [options.leading=true] Specify invoking on the leading edge of the timeout.
 * @param {boolean} [options.trailing=true] Specify invoking on the trailing edge of the timeout.
 * @returns {Function & { cancel: () => void }} Returns the new throttled function with a cancel method.
 */
export function throttle(func, wait, options = {}) {
    let context, args, result;
    let timeoutId = null;
    let previous = 0; // Timestamp of the last execution
    if (!options) options = {};
    const leading = options.leading !== false; // Default true
    const trailing = options.trailing !== false; // Default true

    const later = function () {
        previous = leading === false ? 0 : Date.now(); // Reset previous if leading is false
        timeoutId = null;
        result = func.apply(context, args); // Execute the function
        if (!timeoutId) context = args = null; // Clear references if no pending timeout
    };

    const throttled = function () {
        const now = Date.now();
        // If leading is false and this is the first call, set previous to now
        if (!previous && leading === false) previous = now;

        const remaining = wait - (now - previous);
        context = this;
        args = arguments;

        if (remaining <= 0 || remaining > wait) {
            // If time expired or system clock changed drastically
            if (timeoutId) {
                clearTimeout(timeoutId);
                timeoutId = null;
            }
            previous = now;
            result = func.apply(context, args); // Execute immediately
            if (!timeoutId) context = args = null;
        } else if (trailing && !timeoutId) {
            // Schedule trailing call if option enabled and no timer currently pending
            timeoutId = setTimeout(later, remaining);
        }
        return result;
    };

    throttled.cancel = function () {
        clearTimeout(timeoutId);
        previous = 0;
        timeoutId = context = args = null;
    };

    return throttled;
}

/**
 * Renders LaTeX mathmode inside a given span element, but only if the new label
 * text is different from the previously rendered text (stored in dataset).
 * Handles clearing old content and potential KaTeX errors.
 * @param {HTMLSpanElement} spanElement - The target span element.
 * @param {string | null | undefined} newLabelText - The raw LaTeX string (no delimiters) or null/empty to clear.
 * @param {boolean} textMode - Start in text mode or in math mode (default).
 * @param {boolean} forceRender - Render anyway even if label was unchanged.
 */
export function renderSpanMath(
    spanElement,
    newLabelText,
    textMode = false,
    forceRender = false
) {
    if (!spanElement) return; // Safety check

    const currentLabel = newLabelText ?? '';

    if (typeof katexRender === 'undefined') {
        // Caller forgot to load katex
        spanElement.textContent = currentLabel;
        return;
    }

    // For text mode, we also need the auto-render extension.
    if (textMode && typeof renderMathInElement === 'undefined') {
        console.warn(
            'KaTeX auto-render extension not loaded for text mode rendering.'
        );
        spanElement.innerHTML = currentLabel;
        return;
    }

    const previousLabel = spanElement.dataset.renderedLabel || '';
    const currentMode = textMode ? 'text' : 'math';
    const previousMode = spanElement.dataset.renderedMode || currentMode;

    // Avoid re-rendering if no change in content or mode
    if (
        currentLabel === previousLabel &&
        currentMode === previousMode &&
        !forceRender
    )
        return;

    // Update stored label and mode first
    spanElement.dataset.renderedLabel = currentLabel;
    spanElement.dataset.renderedMode = currentMode;

    // Clear existing content
    spanElement.innerHTML = '';
    if (!currentLabel) return;

    try {
        if (textMode) {
            spanElement.innerHTML = currentLabel;
            renderMathInElement(spanElement, {
                delimiters: [{ left: '$', right: '$', display: false }],
                throwOnError: false,
            });
        } else {
            katexRender(currentLabel, spanElement, {
                throwOnError: false,
                displayMode: false,
            });
        }
    } catch (e) {
        console.error('KaTeX render error:', e, '| Input:', currentLabel);
        spanElement.textContent = currentLabel; // Fallback on error
    }
}

// ========================================================================
// Numerics
// ========================================================================

export function linspace(start, end, numPoints) {
    if (numPoints < 2) {
        return numPoints === 1 ? [start] : [];
    }
    const arr = [];
    const step = (end - start) / (numPoints - 1);
    for (let i = 0; i < numPoints; i++) {
        arr.push(start + step * i);
    }
    return arr;
}

/**
 * The point at a fraction `frac` (0..1) along a polyline's x-extent, with y
 * linearly interpolated between the bracketing vertices. Assumes `xs` is
 * non-decreasing. Returns `{x, y}` (or null for an empty polyline).
 *
 * Shared by the trace classes to place trace labels and the refShift glyph —
 * the same "walk to tx, interpolate y" was previously inlined in BandDiagram
 * (twice) and XYPlot.
 */
export function interpAtFrac(xs, ys, frac) {
    const n = xs.length;
    if (n === 0) return null;
    if (n === 1) return { x: xs[0], y: ys[0] };
    const tx = xs[0] + frac * (xs[n - 1] - xs[0]);
    let ty = ys[n - 1]; // default: past the last vertex → the end value
    for (let k = 1; k < n; k++) {
        if (tx <= xs[k]) {
            const t =
                xs[k] === xs[k - 1] ? 0 : (tx - xs[k - 1]) / (xs[k] - xs[k - 1]);
            ty = ys[k - 1] + t * (ys[k] - ys[k - 1]);
            break;
        }
    }
    return { x: tx, y: ty };
}

/**
 * Throws if `extra` (a `...extraFields` rest object from a def destructure) has
 * any keys — the shared "reject unknown fields" typo-guard used by every
 * updateTraceData / setSpatialLayout / updateVerticalMarkers. No-op when empty.
 */
export function rejectUnexpectedFields(extra) {
    const keys = Object.keys(extra);
    if (keys.length > 0)
        throw new Error('Unexpected fields were provided: ' + keys.join(', '));
}

// ========================================================================
// Controls
// ========================================================================

/**
 * Wires an already-present (static-HTML) <input type="range"> to a throttled
 * callback. The markup must exist in the page at load time — we never inject it
 * from JS, to avoid layout shift. Pair with the `slider` njk macro in
 * `_includes/macros/controls.njk`.
 *
 * @param {string} id - id of the range input element.
 * @param {(value:number, event:Event|null)=>void} onInput - called with the parsed numeric value.
 * @param {object} [opts]
 * @param {number} [opts.throttleMs=100] - throttle interval in ms; 0 disables throttling.
 * @param {boolean} [opts.fire=true] - also invoke onInput once immediately with the initial value.
 * @returns {HTMLInputElement} the slider element.
 */
export function makeSlider(id, onInput, { throttleMs = 100, fire = true } = {}) {
    const el = document.getElementById(id);
    if (!el) throw new Error(`makeSlider: no element #${id}`);
    const call = (event) => onInput(parseFloat(el.value), event);
    el.addEventListener('input', throttleMs ? throttle(call, throttleMs) : call);
    if (fire) onInput(parseFloat(el.value), null);
    return el;
}

// ========================================================================
// bandScale — a band scale with sane padding semantics
// ========================================================================

/**
 * Replacement for d3.scaleBand with predictable semantics (d3's version
 * clamps its step formula with max(1, n - paddingInner + 2*paddingOuter),
 * so with a single band paddingOuter is silently ignored and the band can
 * never fill the range — see d3-scale/src/band.js).
 *
 * Here paddings are fractions of the BANDWIDTH and everything tiles the
 * range exactly:  range = [padL][bw][padIn][bw]...[bw][padR]
 * so paddingInner only matters for n >= 2, paddingOuter works for ALL n,
 * and with paddingOuter=0 the outer band edges sit exactly on the range
 * ends (no hidden leftover, hence no align knob at all).
 *
 * Paddings can also carry PIXEL MINIMUMS (labels are pixel-sized objects in
 * a proportionally-scaled geometry, so pure-relative paddings collapse under
 * responsive squeeze):  each padding is max(relative*bw, minPx), i.e. a
 * minmax() crossover. minPaddingOuter takes a number or {left, right}.
 * paddingOuter(0) + minPaddingOuter({right: 60}) = "always exactly 60px of
 * label room on the right" (the honest version of the old align(0.25) hack).
 *
 * Duck-type compatible with d3-axis (callable + domain/range/bandwidth/copy).
 */
export function bandScale() {
    let domainVals = [];
    let r0 = 0,
        r1 = 1;
    let pIn = 0,
        pOut = 0;
    let minIn = 0,
        minL = 0,
        minR = 0;
    let index = new Map();
    let bw = 0,
        stepv = 0;

    function rescale() {
        const n = domainVals.length;
        if (n === 0) {
            index = new Map();
            bw = stepv = 0;
            return scale;
        }
        const W = r1 - r0;
        // Solve n*bw + (n-1)*max(pIn*bw, minIn) + max(pOut*bw, minL)
        //            + max(pOut*bw, minR) = W  for bw.
        // The left side is monotone increasing & piecewise-linear in bw, so
        // enumerate the 2^3 active-constraint cases and keep the consistent one.
        bw = 0;
        for (const iFix of [true, false])
            for (const lFix of [true, false])
                for (const rFix of [true, false]) {
                    const fixed =
                        (iFix ? (n - 1) * minIn : 0) +
                        (lFix ? minL : 0) +
                        (rFix ? minR : 0);
                    const coeff =
                        n +
                        (iFix ? 0 : (n - 1) * pIn) +
                        (lFix ? 0 : pOut) +
                        (rFix ? 0 : pOut);
                    const cand = (W - fixed) / coeff;
                    // consistency: "fixed" constraints must really bind
                    // (min >= relative) and "relative" ones must not.
                    const ok =
                        cand >= 0 &&
                        (iFix
                            ? pIn * cand <= minIn
                            : pIn * cand >= minIn) &&
                        (lFix
                            ? pOut * cand <= minL
                            : pOut * cand >= minL) &&
                        (rFix
                            ? pOut * cand <= minR
                            : pOut * cand >= minR);
                    if (ok) bw = Math.max(bw, cand);
                }
        // Degenerate (container smaller than the fixed minimums): keep a
        // sliver of band rather than going negative.
        if (bw <= 0) bw = Math.max(1, (W - minL - minR) / n);

        const padIn = Math.max(pIn * bw, minIn);
        const padL = Math.max(pOut * bw, minL);
        stepv = bw + padIn;
        index = new Map(
            domainVals.map((d, i) => [d, r0 + padL + i * stepv])
        );
        return scale;
    }

    function scale(d) {
        return index.get(d);
    }

    scale.domain = function (_) {
        return arguments.length
            ? ((domainVals = Array.from(_)), rescale())
            : domainVals.slice();
    };
    scale.range = function (_) {
        return arguments.length
            ? (([r0, r1] = _), (r0 = +r0), (r1 = +r1), rescale())
            : [r0, r1];
    };
    scale.paddingInner = function (_) {
        return arguments.length ? ((pIn = +_), rescale()) : pIn;
    };
    scale.paddingOuter = function (_) {
        return arguments.length ? ((pOut = +_), rescale()) : pOut;
    };
    scale.minPaddingInner = function (_) {
        return arguments.length ? ((minIn = +_), rescale()) : minIn;
    };
    /** number (both sides) or {left, right} in px */
    scale.minPaddingOuter = function (_) {
        if (!arguments.length) return { left: minL, right: minR };
        if (typeof _ === 'number') minL = minR = +_;
        else ({ left: minL = minL, right: minR = minR } = _);
        return rescale();
    };
    scale.bandwidth = () => bw;
    scale.step = () => stepv;
    // d3-axis's band-centering helper calls scale.round(); we don't round.
    scale.round = () => false;
    scale.copy = () =>
        bandScale()
            .paddingInner(pIn)
            .paddingOuter(pOut)
            .minPaddingInner(minIn)
            .minPaddingOuter({ left: minL, right: minR })
            .domain(domainVals)
            .range([r0, r1]);

    return scale;
}

/**
 * Draw a set of capacitor glyphs between pairs of rails, for use inside a
 * BandDiagram custom-draw callback (see BandDiagram.setCustomDrawCallback).
 * Each capacitor is a `<g>` so it inherits drawElements' full lifecycle: it
 * fades in on enter, glides on update (same transition as the traces), and
 * fades out on exit.
 *
 * @param {BandDiagram} plot - the diagram passed to the custom-draw callback.
 * @param {Array<object>} caps - one entry per capacitor:
 *   { id, x, hi, lo, cHi, cLo, pcf? }
 *   id   - stable key (drives enter/update/exit)
 *   x    - position in DATA coordinates (mapped through plot.xScale)
 *   hi,lo- the two rail voltages the capacitor bridges (hi is the upper plate)
 *   cHi,cLo - plate colours for the hi/lo rails
 *   pcf  - optional plate-centre fraction from hi→lo (default 0.5); nudge it
 *          off-centre when the plates would otherwise land on a third rail.
 * @param {object} [opts] - glyph sizing overrides.
 */
export function drawCapacitors(plot, caps, opts = {}) {
    const {
        plateHalfWidth = 13,
        plateGap = 5,
        plateWidth = 3,
        wireColor = '#666',
        wireWidth = 1.5,
        dotRadius = 2.6,
    } = opts;

    const px = (d) => plot.xScale(d.x);
    const yHi = (d) => plot.yScale(d.hi);
    const yLo = (d) => plot.yScale(d.lo);
    const yMid = (d) => plot.yScale(d.hi + (d.pcf ?? 0.5) * (d.lo - d.hi));
    const yTop = (d) => yMid(d) - plateGap / 2;
    const yBot = (d) => yMid(d) + plateGap / 2;

    plot.drawElements({
        parentGroups: plot.customGroup,
        element: 'g',
        cssClass: 'bd-capacitor',
        data: caps,
        dataKey: (d) => d.id,
        onNew: (s) => {
            // Static per-capacitor attributes (colours, weights); positions are
            // set by onUpdateTransition, which runs immediately for new elements.
            s.append('line').attr('class', 'cap-w1').attr('stroke', wireColor).attr('stroke-width', wireWidth);
            s.append('line').attr('class', 'cap-w2').attr('stroke', wireColor).attr('stroke-width', wireWidth);
            s.append('line').attr('class', 'cap-p1').attr('stroke', (d) => d.cHi).attr('stroke-width', plateWidth).attr('stroke-linecap', 'round');
            s.append('line').attr('class', 'cap-p2').attr('stroke', (d) => d.cLo).attr('stroke-width', plateWidth).attr('stroke-linecap', 'round');
            s.append('circle').attr('class', 'cap-d1').attr('r', dotRadius).attr('fill', (d) => d.cHi);
            s.append('circle').attr('class', 'cap-d2').attr('r', dotRadius).attr('fill', (d) => d.cLo);
        },
        onUpdateTransition: (s) => {
            // s is a plain selection for newborns and a transition for updates;
            // .select() propagates either to the children, so the parts animate.
            s.select('.cap-w1').attr('x1', px).attr('x2', px).attr('y1', yHi).attr('y2', yTop);
            s.select('.cap-w2').attr('x1', px).attr('x2', px).attr('y1', yBot).attr('y2', yLo);
            s.select('.cap-p1').attr('x1', (d) => px(d) - plateHalfWidth).attr('x2', (d) => px(d) + plateHalfWidth).attr('y1', yTop).attr('y2', yTop);
            s.select('.cap-p2').attr('x1', (d) => px(d) - plateHalfWidth).attr('x2', (d) => px(d) + plateHalfWidth).attr('y1', yBot).attr('y2', yBot);
            s.select('.cap-d1').attr('cx', px).attr('cy', yHi);
            s.select('.cap-d2').attr('cx', px).attr('cy', yLo);
        },
    });
}
